name: thechnical_assignment_tots
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.6
  riverpod_annotation: ^2.3.5
  dio: ^5.6.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  flutter_localization: ^0.2.2
  flutter_secure_storage: ^9.2.2
  either_dart: ^1.0.0
  flutter_dotenv: ^5.2.1
  email_validator: ^2.1.17
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  image_picker: ^0.8.7+4
  animate_do: ^3.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  riverpod_lint: ^2.3.13
  riverpod_generator: ^2.4.3
  flutter_launcher_icons: ^0.13.1


flutter_icons: 
  android: true 
  ios: true
  image_path: "assets/images/logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/gradients/
    - .env    

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf